"""MCP Benchmark SDK - Build and run LLM agent benchmarks against MCP servers."""

__version__ = "0.1.0"

# Agent system (agents, tasks, runtime, MCP, parsers, telemetry, utils, constants)
from .agents import (
    Agent,
    ClaudeAgent,
    GPTAgent,
    GeminiAgent,
    GrokAgent,
    Task,
    Result,
    AgentResponse,
    ToolCall,
    ToolResult,
    MCPConfig,
    MCPClientManager,
    RunContext,
    RunObserver,
    StatusLevel,
    MessageRole,
    ResponseParser,
    ParsedResponse,
    configure_langfuse,
    configure_langsmith,
    get_langfuse_client,
    get_langfuse_trace_url,
    get_langsmith_client,
    is_langfuse_enabled,
    is_tracing_enabled,
    get_trace_url,
    print_trace_summary,
    with_tracing,
    TracingAgent,
    DEFAULT_TOOL_CALL_LIMIT,
    DEFAULT_MAX_STEPS,
    DEFAULT_LLM_TIMEOUT_SECONDS,
    DEFAULT_LLM_MAX_RETRIES,
    TOOL_CALL_ID_HEX_LENGTH,
    THINKING_SAFETY_MARGIN_TOKENS,
    THINKING_DEFAULT_OUTPUT_TOKENS,
    THINKING_DEFAULT_BUDGET_TOKENS,
    REASONING_MAX_DEPTH,
    REASONING_MAX_TEXT_LENGTH,
    RETRY_BASE_DELAY_SECONDS,
    RETRY_MAX_DELAY_SECONDS,
    RETRY_DEFAULT_MAX_ATTEMPTS,
    RETRY_TRANSIENT_STATUS_CODES,
    derive_sql_runner_url,
)

# SDK-wide constants
from .constants import (
    DATABASE_VERIFIER_TIMEOUT_SECONDS,
    HTTP_CLIENT_TIMEOUT_SECONDS,
)

# Test harness (orchestration, scenarios, verifiers)
from .harness import (
    TestHarness,
    TestHarnessConfig,
    RunResult,
    ResultBundle,
    ModelResultFile,
    infer_platform_from_model,
    HarnessLoader,
    load_harness_file,
    load_harness_directory,
    scenario_to_task,
    create_agent,
    create_traced_agent,
    Scenario,
    ScenarioPrompt,
    VerifierDefinition,
    Verifier,
    DatabaseVerifier,
    VerifierResult,
    ComparisonType,
    compare,
)

__all__ = [
    # Core
    "Agent",
    "Task",
    "Result",
    "RunContext",
    "RunObserver",
    "StatusLevel",
    "MessageRole",
    # Telemetry
    "configure_langfuse",
    "configure_langsmith",
    "get_langfuse_client",
    "get_langfuse_trace_url",
    "get_langsmith_client",
    "is_langfuse_enabled",
    "is_tracing_enabled",
    "get_trace_url",
    "print_trace_summary",
    "with_tracing",
    "TracingAgent",
    # Agents
    "ClaudeAgent",
    "GPTAgent",
    "GeminiAgent",
    "GrokAgent",
    # Tasks
    "AgentResponse",
    "ToolCall",
    "ToolResult",
    # MCP
    "MCPConfig",
    "MCPClientManager",
    # Verifiers
    "Verifier",
    "DatabaseVerifier",
    "VerifierResult",
    "ComparisonType",
    "compare",
    # Test Harness
    "TestHarness",
    "TestHarnessConfig",
    "RunResult",
    "ResultBundle",
    "ModelResultFile",
    "HarnessLoader",
    "load_harness_file",
    "load_harness_directory",
    "scenario_to_task",
    "create_agent",
    "create_traced_agent",
    "Scenario",
    "ScenarioPrompt",
    "VerifierDefinition",
    "infer_platform_from_model",
    # Parsers
    "ResponseParser",
    "ParsedResponse",
    # Constants
    "DEFAULT_TOOL_CALL_LIMIT",
    "DEFAULT_MAX_STEPS",
    "DEFAULT_LLM_TIMEOUT_SECONDS",
    "DEFAULT_LLM_MAX_RETRIES",
    "TOOL_CALL_ID_HEX_LENGTH",
    "THINKING_SAFETY_MARGIN_TOKENS",
    "THINKING_DEFAULT_OUTPUT_TOKENS",
    "THINKING_DEFAULT_BUDGET_TOKENS",
    "REASONING_MAX_DEPTH",
    "REASONING_MAX_TEXT_LENGTH",
    "RETRY_BASE_DELAY_SECONDS",
    "RETRY_MAX_DELAY_SECONDS",
    "RETRY_DEFAULT_MAX_ATTEMPTS",
    "RETRY_TRANSIENT_STATUS_CODES",
    "DATABASE_VERIFIER_TIMEOUT_SECONDS",
    "HTTP_CLIENT_TIMEOUT_SECONDS",
    # Utils
    "derive_sql_runner_url",
]
